spring:
  application:
    name: E-Commerce-Mono-App
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: Ashu@2002
    
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: springbootdemo118@gmail.com
    password: kohqqxtpublszqwl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000

server:
  port: 9999
twilio:
  account-sid: ${account.sid}
  auth-token: ${auth.token}
  phone-number: +15673716166